on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - uses:  ./
      with:
        test-assembly-dll: GameCore.specs/bin/Debug/netcoreapp3.1/RunSpecflowTests.dll
        test-execution-json: GameCore.specs/bin/Debug/netcoreapp3.1/TestExecution.json
        output-html: CalculatorResults.html
        framework: netcoreapp3.1
        configuration: 'Debug'
        logger: trx
        logger-file-name: ../../CalculatorResults.trx
